import type { CurriculumEntry } from '@/types/curriculum'

export const curriculum: CurriculumEntry[] = [
  {
    company: 'holi',
    title: 'Senior Full Stack Engineer',
    companyType: 'Full-Time Employee (50+ employees)',
    companyUrl: 'https://holi.social',
    date: 'Mar 2023 - Dec 2025',
    location: 'Hamburg, Germany · Remote',
    desc: 'The space for positive change. Holi is an app that connects existing social apps and digital tools in one home. One codebase for iOS, Android and Web using a fork of the openSource social network Okuna as backend. Beautiful stack, beautiful people.',
    latestProject: 'https://app.holi.social',
    skills: ['ReactNative', 'NextJS', 'Python', 'Django', 'Expo', 'okuna'],
  },
  {
    company: 'shift-happens',
    title: 'Fullstack Web & Blockchain App Developer',
    companyType: 'Self-employed',
    date: 'Jan 2021 - Present',
    location: 'Cozumel, Quintana Roo, Mexico',
    desc: 'I have worked with JavaScript for over 20 years and always loved web development and the rapid pace of innovation. Seeing JavaScript becoming so ubiquitous over the last years is amazing and I really enjoy the current ecosystem. I am always on the search for interesting projects and am passionate about using my craft to make the world a better place. Other areas of interest include Artificial Intelligence, Robotics, Blockchain and Low Level Programming with Arduino/RaspberryPie.',
    latestProject: 'https://moonshire.vercel.app/',
    skills: ['React', 'Node', 'Solidity', 'Smart contracts', 'APIs', 'NextJS', 'Svelte(Kit)', 'React Native', 'Supabase'],
  },
  {
    company: 'shift-happens Yoga',
    title: 'Yoga Teacher',
    companyType: 'Self-employed',
    date: 'Jan 2018 - Present',
    location: 'Thailand, Indonesia, India, Nepal, Mexico, ...',
    desc: 'In 2018, struggling with burnout, I quit my job as developer in Barcelona, started travelling the world and discovered Yoga. I enrolled in a 200h Yoga teacher training course in Thailand. An eye-opening experience that changed my life forever. I have been practicing and teaching Yoga since. The name shift_happens is based on the immense sudden shift my life took when Yoga entered my life and from the prospect that Yoga can help to heal. I am also Yoga Alliance RYT-500 and ERYT-200 certified.',
    latestProject: 'https://yoga.christof.digital/',
    skills: ['Ashtanga primary & intermediate series', 'Yoga for Martial Artists', 'Anatomy for Yoga and TTCs', 'Pranayama', 'Pre-YTT trainings', 'Yoga and mental health'],
  },
  {
    company: 'XING AG',
    title: 'Frontend Engineer',
    companyType: 'Full-Time Employee (1000+ employees)',
    companyUrl: 'https://www.xing.com/',
    date: 'Aug 2014 - Jan 2018',
    duration: '3 years 6 months',
    location: 'Hamburg, Germany',
    desc: 'Xing is the LinkedIn of the German-speaking market. It is now a unicorn, with more than a 1000 employees over 5 countries, but still felt like a startup. I joined the headquarters in Hamburg as Frontend Engineer for the Premium/ProJobs team. It was a great, enthusiastic atmosphere and until today my longest commitment towards a company. In late 2016 I switched to our newly opened Barcelona office to support and build up the team. Fun fact: Xing was supposed to be pronounced Crossing/X-ing, but instead the German public just calls it Xing with a hard X. Entertaining marketing-fail 101.',
    latestProject: 'https://www.xing.de/projobs',
    skills: ['React', 'Git', 'TravisCI', 'Scrum', 'Kanban'],
  },
  {
    company: 'Gruner + Jahr GmbH & Co KG',
    title: 'System Engineer',
    companyType: 'Full-Time Employee (1,500+ employees)',
    companyUrl: 'https://www.guj.de/',
    date: 'Oct 2012 - Jul 2014',
    duration: '1 year 10 months',
    location: 'Hamburg, Germany',
    desc: 'G&J is (was) the biggest publishing company in Germany with titles like National Geographic, Financial Times Deutschland or Stern. G&J hosted all its infrastructure in house (crazy, I know) and as part of G+J Digital Products we were responsible for keeping it all running... 24/7. Another task was to provide all dev and staging environments for the different teams, deployments, build chains, security, virtualization... G&J was a traditional, huge company and very slow to adjust to challenges of the new digital age, still it was an immensely valuable learning experience for me.',
    latestProject: 'Production Setup for Brigitte.de, Gala.de, Geo.de. ',
    skills: ['Shell', 'Perl', 'PHP', 'VMWare', 'Apache', 'NGinx'],
  },
  {
    company: 'Futura Epsis 1',
    title: 'Senior Lead Developer',
    companyType: 'Self-employed',
    companyUrl: 'https://www.futura-epsis1.com/',
    date: 'Apr 2012 - Sep 2012',
    duration: '6 months',
    location: 'Hamburg, Germany',
    desc: 'With the digital artist I mentioned earlier, we created digital experiences for brands, agencies, art curators, labels and musicians. Whereas he was creating the art, I was responsible for all backend related tasks. One project was to develop a massive multitouch table, working with a beamer and resistive touchscreen - but in March of the same year Apple launched the iPad and pretty much made all these ideas obsolete. Our cooperation was nonetheless a fruitful endeavor.',
    latestProject: 'Multitouch device just before the iPad launched...',
    skills: ['ActionScript', 'PHP', 'Apache', 'jQuery'],
  },
  {
    company: 'Trakken Technologies GmbH',
    title: 'Web-Developer',
    companyUrl: 'https://www.trakkenwebservices.com/',
    companyType: 'Full-Time Employee (~10 employees)',
    date: 'Feb 2010 - May 2012',
    duration: '2 years 4 months',
    location: 'Hamburg, Germany',
    desc: 'In early 2010 I joined the just founded startup Trakken Technologies, becoming part of a 3-person dev team. It was wild, fiddling with JavaScript, setting up and managing our own servers, failing deployments on Friday, the usual early quirks. Main product was TrakkBoard, a SaaS solution for web controlling, a sort of digital data platform, the analytics for marketers. It&apos;s still out there.',
    latestProject: 'https://www.trakkenwebservices.com/products/trakkboard/',
    skills: ['Ruby on Rails', 'PHP', 'Hadoop', 'jQuery', 'MongoDB', 'HBase', 'redis'],
  },
  {
    company: 'thirtyOne Media',
    title: 'PHP & ActionScript Programmer',
    companyType: 'Freelance',
    companyUrl: 'https://thirtyonedigital.com/',
    date: 'Oct 2008 - Feb 2010',
    duration: '1 year 5 months',
    location: 'Hamburg, Germany',
    desc: 'This was my first real attempt to do more independent projects as a freelancer. I partnered with Andreas Rothaug, a digital artist from Hamburg - together we built RIAs (Rich Internet Applications) with a Flash frontend and a PHP backend. Our clients were mainly digital marketing agencies and affiliates.',
    latestProject: 'Gateway between Flash (ActionScript3) and PHP with AMF',
    skills: ['ActionScript3', 'PHP', 'LAMP', 'Zend'],
  },
  {
    company: 'eSearchVision',
    title: 'SEM Account Manager',
    companyType: 'Full-Time Employee (~40 employees)',
    companyUrl: 'https://www.esvdigital.com/',
    date: '2007 - 2008',
    duration: '1 year',
    location: 'Paris, France',
    desc: 'Founded in 2004 and expanding to the US in 2006, I worked at eSV as SEM Manager on ad campaigns for clients like Apple, Scout24 or Filemaker, mainly for the German market. This was quite an intense, KPI driven environment, but at the same time very insightful to work in a truly international team. For me, this was the first time that English was the main company language.',
    latestProject: 'Apple Product Red campaign',
    skills: ['AdSense', 'Analytics', 'Target CPC optimization'],
  },
  {
    company: 'Pangora SAS',
    title: 'SEM Manager',
    companyType: 'Full-Time Employee (~40 employees)',
    date: 'May 2007 - Oct 2007',
    duration: '6 months',
    location: 'Paris, France',
    desc: "This was my first &apos;real&apos; job after graduating! Additionally, in a new city in a whole new country: Paris, France. Well, not really, I used to live there in my childhood. But this time, I came for something different. I worked in Search Engine Marketing (SEM), mostly for price comparison sites. (buycentral.de, shopping.lycos.de...). Very analytical position trying to optimize CPC/CPO for longtail searchterms.",
    latestProject: '',
    skills: ['AdSense', 'CPC optimization'],
  },
  {
    company: 'mentasys GmbH',
    title: 'Graduand',
    companyType: 'Full-Time Employee (~40 employees)',
    date: '2006 - 2007',
    duration: '1 year',
    location: 'Karlsruhe, Germany',
    desc: 'I had the chance to write my Master Thesis about building web shops within a company called mentasys, owner of the biggest online portal for gifts in Germany at that time, youSmile.de. I completely rebuild and redesigned the portal using a PHP backend, MySQL database and an IE6 optimized frontend - yes, it was that time. Biggest challenge was debugging jQuery (which was brand new) and database performance, where mysql stored procedures and MqSQLi came to the rescue. It was my biggest project until then.',
    latestProject: 'Technical and conceptual Redesign and Relaunch of the Web portal youSmile.de',
    skills: ['HTML', 'MySQL', 'PHP', 'jQuery'],
  },
]
