import type { Project } from '@/types'

export const projects: Project[] = [
  {
    name: 'Solo Mining Dashboard  ',
    desc: 'A real-time monitoring dashboard for the NerdQaxe++ Bitcoin Solo Miner and similar ESP based devices.',
    tech: ['websocket', 'Node.js', 'ASIC'],
    image: 'dashboard.png',
    link: 'https://github.com/Existenziell/miner-dashboard',
    linkText: 'Solo Mining Dashboard',
    external: true,
  },
  {
    name: 'Bitcoindev.info',
    desc: 'Bitcoin development guide for developers. Open source documentation, CLI terminal, Stack Lab, Block Visualizer. No ads. Always free.',
    tech: ['Script', 'Bitcoin', 'RPC/CLI'],
    image: 'bitcoindev.png',
    link: 'https://bitcoindev.info/',
    linkText: 'Bitcoindev.info',
    external: true,
  },
  {
    name: 'Bitcoin Blockchain Monitoring',
    desc: 'A suite of Python tools for monitoring Bitcoin blockchain activity and pool mining.',
    tech: ['Python', 'ZMQ', 'Blockchain'],
    image: 'monitoring.png',
    link: 'https://github.com/Existenziell/chain-monitor',
    linkText: 'Bitcoin Monitoring Suite',
    external: true,
  },
  {
    name: 'Sucré Salé Bakery',
    desc: 'Just a simple yet beautiful and performant website, built as PWA and seeing quite some traffic.',
    tech: ['i18n', 'QR Codes', 'Admin Dashboard'],
    image: 'sucre.webp',
    link: 'https://sucre-sale.vercel.app/',
    linkText: 'Sucré Salé Bakery',
    external: true,
  },
  {
    name: 'Rick&Morty API',
    desc: 'Using react-query and the open Rick&Morty API to test clearer data flow without useEffect().',
    tech: ['react-query', 'Pagination', 'Search'],
    image: 'rick.webp',
    link: '/programming/projects/api',
    linkText: 'Rick&Morty API',
    external: false,
  },
  {
    name: 'RateMe',
    desc: 'A fresh approach to customer care. App for restaurants to rate customers for more transparency.',
    tech: ['framer-motion', 'Mapbox', 'Microservices'],
    image: 'rateme.webp',
    link: 'https://rate-me-cozumel.vercel.app/',
    linkText: 'RateMe',
    external: true,
  },
  {
    name: 'Cozumel Taxonomy',
    desc: 'A taxonomy app for the island of Cozumel in Mexico to raise awareness for endangered endemic species.',
    tech: ['useSWR', 'iNaturalist API', 'Taxonomy'],
    image: 'cozumon.webp',
    link: 'https://cozumel-taxonomy.vercel.app/',
    linkText: 'Cozumel Taxonomy',
    external: true,
  },
  {
    name: 'CZMStem Clinic',
    desc: 'App for a stem cell clinic with user management, payments and health data visualisation.',
    tech: ['Plaid API', 'ThreeJS', 'NextJS'],
    image: 'czmstem.webp',
  },
  {
    name: 'ThreeJS Game',
    desc: 'Stack game with Three.js and Cannon.js. Venturing into WebGL and game physics.',
    tech: ['ThreeJS', 'WebGL', 'Game Physics'],
    image: 'threejs.webp',
    link: '/programming/projects/threejs',
    linkText: 'ThreeJS Game',
    external: false,
  },
  {
    name: 'Annapurna Trek Map',
    desc: "Website built with Mapbox, trying to display some impressions from the longest trek I've done so far.",
    tech: ['Mapbox', 'Geolocation', 'Clustering'],
    image: 'annapurna.webp',
    link: 'https://annapurna-trek-map.vercel.app/',
    linkText: 'Annapurna Trek Map',
    external: true,
  },
  {
    name: 'Moonshire NFT platform',
    desc: 'Moonshire is a web3 platform, a decentralised service for content creators running on the Blockchain.',
    tech: ['Solidity', 'ether.js', 'hardhat', 'NFTs'],
    image: 'moonshire.webp',
    link: 'https://moonshire.vercel.app/',
    linkText: 'Moonshire NFT platform',
    external: true,
  },
  {
    name: 'AI Image Generation',
    desc: "The future is here. Testing the possibilities of AI image generation with Dall-E and stable diffusion.",
    tech: ['Dall-E', 'stable diffusion', 'AI'],
    image: 'ai.webp',
    link: '/programming/projects/ai',
    linkText: 'AI Image Generation',
    external: false,
  },
]
