import type { Teaching } from '@/types'

export const teachings: Teaching[] = [
    {
        date: '2019 - today',
        title: 'Yoga Teacher',
        description: 'I discovered Yoga in 2017 and was instantly fascinated by it. I was used to dealing with my issues with my brain, not listening to my body. Yoga changed that and gave me new tools to deal with my internal struggles. It has helped me tremendously and I love to share this knowledge with others. I am Yoga Alliance RYT-500 and ERYT-200 certified.',
        image: 'yoga.jpg',
        link: '/teaching/yoga',
        linkText: 'Shift Happens Yoga',
        external: false,
    },
    {
        date: '2004 - today',
        title: 'Language Teacher',
        description: 'I am fluent in English, French and German and have been teaching these languages in a private setting for many years. I just love languages - they open up a whole new world of possibilities. Communication is the key to understanding the world.',
        image: 'language-teacher.jpg',
    },
    {
        date: '2018 - today',
        title: 'Slackline Workshops',
        description: 'I absolutely love slacklining and have been teaching slackline workshops for many years. The art of balancing a tight rope is a beautiful way to reach flow states and connect with the present moment. Have you ever tried it? Do you want a defined body shape? No need for gyms, just slackline! It is so much fun! Contact me :) ',
        image: 'slackline.jpg',
    },
    {
        date: 'March 2024',
        title: 'Workshop at Bitcoin Atlantis Conference',
        description: 'I had the honor to teach a workshop at the Bitcoin Atlantis Conference on Madeira Island. Introducing the basics of Bitcoin, Lightning, Transactions, UTXOs and the beautiful potential of this open source technology.',
        image: 'bitcoin-atlantis.png',
        link: 'https://bitcoinatlantis.com/',
        linkText: 'Bitcoin Atlantis Conference',
        external: true,
    },
    {
        date: '2023 - 2024',
        title: 'Teacher for the Hacker School',
        description: 'I worked with the Hacker School (Germany) as a teacher - kindling the curiosity of students for algorithms and computer science. I introduced them to the basics of software engineering and programming languages, data structures and databases. It is incredibly rewarding to see students succeed with their ideas.',
        image: 'hacker-school.png',
        link: 'https://hacker-school.de/',
        linkText: 'Hacker School',
        external: true,
    },
    {
        date: 'May 2019',
        title: 'Volunteer for the Bali Children Foundation',
        description: 'The Bali Children Foundation helps thousands of disadvantaged children in Bali to complete school, to find employment, and to improve their lives and the life of their community. I volunteered to do Yoga classes with the children, twice! It was one of the most incredible experiences of my life. Children are the best!',
        image: 'bali-children-foundation.png',
        link: 'https://www.balichildrenfoundation.org/',
        linkText: 'Bali Children Foundation',
        external: true,
    },
    {
        date: '2003 - 2006',
        title: 'Learning institute for customized education',
        description: 'The Lernstudio Barbarossa is a learning institute helping students with their homework and studies. During my computer science studies at the HKA, I worked as a tutor for the subjects Mathematics, Physics, Programming and Foreign Languages (English, French, German). Trying to convey knowledge so that it can be understood by the counterpart, truly is an art.',
        image: 'lernstudio-barbarossa.png',
        link: 'https://www.lernstudio-barbarossa.de/en/locations/karlsruhe/',
        linkText: 'Lernstudio Barbarossa',
        external: true,
    },
]