export const curriculum = [
  {
    company: "Dream Factory Cozumel",
    title: "Fullstack Blockchain App Developer",
    companyType: "Self-employed",
    date: "Aug 2021 – Present",
    duration: "4 months",
    location: "Cozumel, Quintana Roo, Mexico",
    desc: "Venturing into the realms of the blockchain.",
    latestProject: "https://deez-nutz-dapp.vercel.app/",
    skills: ["Solidity", "Web3", "ethers.js", "hardhat", "truffle"],
  },
  {
    company: "shift-happens",
    title: "Full Stack Engineer",
    companyType: "Self-employed",
    date: "Jan 2021 – Present",
    duration: "11 months",
    location: "Cozumel, Quintana Roo, Mexico",
    desc: "Remote work, many interesting projects!",
    latestProject: "https://www.czmstem.com/",
    skills: ["Web/Fullstack/Mobile", "NextJS", "Svelte", "Tailwind", "Parcel", "Vercel", "JamStack"],
  },
  {
    company: "shift_happens_yoga",
    title: "Yoga Teacher",
    companyType: "Self-employed",
    date: "Jan 2018 – Present",
    duration: "3 yrs 11 months",
    location: "Thailand, Indonesia, India, Nepal, ...",
    desc: "Working as full-time Yoga teacher. Yoga alliance RYT-500 and ERYT-200 certified.",
    latestProject: "https://www.christof.digital/yoga",
    skills: ["Ashtanga Vinyasa Yoga", "Pre-YTT trainings", "Yoga for Martial Artists", "Anatomy for Yoga and Alignments", "Pranayama"]
  },
  {
    company: "XING AG",
    title: "Frontend Engineer",
    companyType: "Full-Time Employee (1000+ employees)",
    date: "Aug 2014 – Jan 2018",
    duration: "3 years 6 months",
    location: "Hamburg, Germany",
    desc: "Wonderful atmosphere in this unicorn startup!",
    latestProject: "https://www.xing.de/projobs",
    skills: ["React", "Scrum"]
  },
  {
    company: "Gruner + Jahr GmbH & Co KG",
    title: "System Engineer",
    companyType: "Full-Time Employee (1,500+ employees)",
    date: "Oct 2012 – Jul 2014",
    duration: "1 year 10 months",
    location: "Hamburg, Germany",
    desc: "Quirks...",
    latestProject: "Production Setup for Brigitte.de, Gala.de, Geo.de. ",
    skills: ["Shell", "Perl", "PHP", "Apache", "NGinx"]
  },
  {
    company: "Futura Epsis 1",
    title: "Senior Lead Developer",
    companyType: "Self-employed",
    date: "Apr 2012 – Sep 2012",
    duration: "6 months",
    location: "Hamburg, Germany",
    desc: "With my partner (a godlike designer) we created digital experiences to connect to a person on an emotional level.",
    latestProject: "Multitouch device just before the iPad launched...",
    skills: ["ActionScript", "PHP", "Apache", "JQuery"]
  },
  {
    company: "Trakken Technologies GmbH",
    title: "Developer on PHP, Ruby, JavaScript",
    companyType: "Full-Time Employee (~20 employees)",
    date: "Feb 2010 – May 2012",
    duration: "2 years 4 months",
    location: "Hamburg, Germany",
    desc: "Development of <a href='https://www.trakkenwebservices.com/products/trakkboard/' target='_blank'>TrakkBoard</a>, a new software as a service solution for web controlling built on cloud computing.",
    latestProject: "TrakkBoard",
    skills: ["Ruby on Rails", "PHP", "Vanilla JS", "JQuery"]
  },
  {
    company: "thirtyOne Media",
    title: "PHP & ActionScript Programmer",
    companyType: "Self-employed",
    date: "Oct 2008 – Feb 2010",
    duration: "1 year 5 months",
    location: "Hamburg, Germany",
    desc: "We build RIA (Rich Internet Applications) with a Flash frontend and a PHP backend.",
    latestProject: "Gateway between Flash (ActionScript3) and PHP with AMF",
    skills: ["ActionScript3", "PHP", "LAMP", "Zend"]
  },
  {
    company: "eSearchVision",
    title: "SEM Account Manager",
    companyType: "Full-Time Employee (~40 employees)",
    date: "2007 – 2008",
    duration: "1 year",
    location: "Paris, France",
    desc: "SEM Manager on Ad campaigns for clients like Apple, Scout24 or Filemaker.",
    latestProject: "Apple Product Red campaign",
    skills: ["AdSense", "Yahoo", "MSN"]
  },
  {
    company: "Pangora SAS",
    title: "SEM Manager",
    companyType: "Full-Time Employee (~40 employees)",
    date: "May 2007 – Oct 2007",
    duration: "6 months",
    location: "Paris, France",
    desc: "  Search Engine Marketing (SEM) for price comparison sites. (buycentral.de, shopping.lycos.de...)    ",
    latestProject: "Long tail optimizations.",
    skills: []
  },
  {
    company: "mentasys GmbH",
    title: "Graduand",
    companyType: "Full-Time Employee (~40 employees)",
    date: "2006 – 2007",
    duration: "1 year",
    location: "Karlsruhe, Germany",
    desc: "I wrote my Master Thesis about building webshops. mentasys needed one and supported my work to finalize the web portal youSmile.de.",
    latestProject: "Technical and conceptual Redesign and Relaunch of the Web portal youSmile.de",
    skills: ["HTML", "CSS2", "PHP", "JQuery"]
  },
]
