export const projects = [
  {
    name: "AI Image Generation",
    desc: "The future is here. Testing the possibilities of AI image generation with Dall-E and stable diffusion.",
    tech: ['Dall-E', 'stable diffusion', 'AI'],
    image: "ai.webp",
    link: "/ai",
  },
  {
    name: "Annapurna Trek Map",
    desc: "Trying to put the biggest trek I've done so far into a compelling Mapbox app.",
    tech: ['Mapbox', 'Geolocation', 'JSON API'],
    image: "annapurna.webp",
    link: "https://annapurna-trek-map.vercel.app/",
  },
  {
    name: "Moonshire NFT platform",
    desc: "Moonshire is a web3 platform, a decentralised monetising service for content creators running on the Blockchain.",
    tech: ['Solidity', 'Blockchain', 'ether.js', 'hardhat', 'NFTs'],
    image: "moonshire.webp",
    link: "https://moonshire.vercel.app/",
  },
  {
    name: "CZMStem Clinic",
    desc: "An app for the stem cell clinic CMZStem, featuring a dashboard for health data visualisation.",
    tech: ['Plaid API', 'ThreeJS'],
    image: "czmstem.webp",
    link: "https://www.czmstem.com/",
  },
  {
    name: "Dog's Paradise App",
    desc: "Web App for a dogs daycare Spa with admin dashboard, social elements and PWA.",
    tech: ['Supabase', 'Multilingual'],
    image: "dogs.webp",
    link: "https://dogs-paradise.vercel.app/",
  },
  {
    name: "Sucré Salé Bakery Website",
    desc: "Just a simple yet beautiful and performant website, built as PWA.",
    tech: ['i18n', 'QR Codes', 'Admin Dashboard'],
    image: "sucre.webp",
    link: "https://sucre-sale.vercel.app/",
  },
  {
    name: "Rick&Morty API",
    desc: "Using react-query and the open Rick&Morty API to test Pagination.",
    tech: ['react-query', 'Mutations', 'NextJS', 'TailwindCSS'],
    image: "rick.webp",
    link: "/play",
  },
  {
    name: "Cozumon",
    desc: "A taxonomy app for the island of Cozumel in Mexico to raise awareness for endangered endemic species.",
    tech: ['useSWR', 'iNaturalist API', 'NextJS', 'PWA'],
    image: "cozumon.webp",
    link: 'https://cozumon.vercel.app/',
  },
]
