/**
 * Design tokens: single source for Tailwind and CSS.
 * CSS vars are generated by scripts/generate-theme-css.js → styles/_theme-vars.css
 * Mauve: 12-step scale with very small steps (Radix-style soft purple-grey).
 */
const colors = {
  brand: '#DBDBDB',
  brandDark: '#242424',
  cta: '#D6A269',
  gray: '#EBEBEB',
  grayDark: '#323232',
  svgDark: '#635bff',
  svgLight: '#80e9ff',
}

/** Mauve scale: 12 steps, small shade increments (lightest 1 → darkest 12) */
const mauve = {
  1: '#fdfcfd',
  2: '#faf9fb',
  3: '#f6f4f8',
  4: '#f0eef3',
  5: '#eae7ed',
  6: '#e3dfe6',
  7: '#ddd8e0',
  8: '#d2cdd7',
  9: '#c4bfc9',
  10: '#a8a3ae',
  11: '#6e6a75',
  12: '#2d2b30',
}

const light = {
  pageBg: mauve[1],
  sectionBg: mauve[1],
  sectionAlt: mauve[2],
  surface: '#ffffff', /* cards elevated on mauve page */
  surfaceMuted: mauve[3],
  textPrimary: mauve[12],
  textMuted: mauve[11],
  border: mauve[6],
  headerBg: mauve[2],
  headerFg: mauve[12],
}

/** Dark mauve scale: same hue, darker range */
const mauveDark = {
  1: '#1c1b1f',
  2: '#232225',
  3: '#2a282d',
  4: '#312f34',
  5: '#38363c',
  6: '#403d44',
  7: '#48454c',
  8: '#504d55',
  9: '#5f5c66',
  10: '#8b8792',
  11: '#b5b0bc',
  12: '#e6e1e9',
}

const dark = {
  pageBg: mauveDark[1],
  sectionBg: mauveDark[1],
  sectionAlt: mauveDark[2],
  surface: mauveDark[3],
  surfaceMuted: mauveDark[4],
  textPrimary: mauveDark[12],
  textMuted: mauveDark[10],
  border: mauveDark[6],
  headerBg: mauveDark[2],
  headerFg: mauveDark[12],
}

module.exports = {
  colors,
  mauve,
  mauveDark,
  light,
  dark,
}
