/**
 * Design tokens: single source for Tailwind and CSS.
 * CSS vars are generated by scripts/generate-theme-css.js → styles/_theme-vars.css
 */
const colors = {
  brand: '#DBDBDB',
  brandDark: '#242424',
  cta: '#D6A269',
  gray: '#EBEBEB',
  grayDark: '#323232',
  svgDark: '#635bff',
  svgLight: '#80e9ff',
}

module.exports = { colors }
